### ISSUE TITLE
Unable to download "genefamily " file

### ISSUE THREAD

**Issue by DPC7** [waldronlab/curatedMetagenomicDataCLI#12]
Hi @schifferl  @lwaldron - I am writing this issue in connection with a [previous issue of mine](https://github.com/waldronlab/curatedMetagenomicDataTerminal/issues/8). I am using the following command after reinstalling the full package but it is just showing data on the terminal screen but not getting downloaded in my computer. Can you please help?
**Command:**
`$curatedMetagenomicData "2021-03-31.AsnicarF_2021.relative_abundance"`

Thanks,
DPC7

**Comment by schifferl** [comment]
Hi @DPC7, the behavior you described is expected (i.e. data at the terminal screen via `stdout`). The change was made to allow for piping and redirection. If you want to create a TSV file, just redirect to a file as follows.

```{sh}
curatedMetagenomicData "AsnicarF_2021.relative_abundance" > AsnicarF_2021.relative_abundance.tsv
```

Please let me know if this solves your issue. Thanks, Lucas

**Comment by DPC7** [comment]
> Hi @DPC7, the behavior you described is expected (i.e. data at the terminal screen via `stdout`). The change was made to allow for piping and redirection. If you want to create a TSV file, just redirect to a file as follows.
> 
> ```
> curatedMetagenomicData "AsnicarF_2021.relative_abundance" > AsnicarF_2021.relative_abundance.tsv
> ```
> 
> Please let me know if this solves your issue. Thanks, Lucas

Thanks, @schifferl . It runs for a while but after a few minutes, it is "killed" automatically without the file getting downloaded.

**Comment by schifferl** [comment]
Hi @DPC7, I would need more info to help you... What do you mean by "killed"? There is no file after you do `ls`? I am sure the software is working correctly, so you issue may have to do with an internet connection or be related to your specific configuration. Are you able to download other resources?

**Comment by DPC7** [comment]
It just stops running in the terminal and shows "killed". While I tried to download the "relative abundance" file, it is downloading perfectly.
```
(base) deep@deep:~/Desktop/Asnicar$ curatedMetagenomicData "2021-03-31.AsnicarF_2021.gene_families" > genefamilies.tsv 
Killed
```



Thanks

**Comment by schifferl** [comment]
Hi @DPC7, you put two separate commands and thus the confusion. I not sure, but I am going to guess you are running out of memory. All gene families resources are exceptionally large sparse matrices that must be realized as regular matrices, transposed, and coerced into TSV format. To return the smaller `AsnicarF_2017.gene_families` (24 samples) required ~ 25 GB of RAM and returned a file ~ 1 GB in size when I attempted it; the larger `AsnicarF_2017.gene_families` (1,098 samples) I did not attempt. Unless you are working with some serious hardware, you'll need to use R and the sparse matrix format for your task.

**Comment by DPC7** [comment]
Sir, @schifferl - my computer has a 64GB of RAM. I am not that familiar with R. Can you please tell me if there is a way to get the .tsv file via R? I don't need information for all the samples. Just the samples from "Country=GBR" is required. Can you please help?

**Comment by lwaldron** [comment]
@DPC7 you should have enough RAM, but I notice this big dataset takes a very long time just to do anything with,  even just to serialize from ExperimentHub. I've succeeded in writing a MatrixMarket format sparse matrix to file like this:

```r
library(curatedMetagenomicData)
curatedMetagenomicData("AsnicarF_2021.gene_families")
## 2021-03-31.AsnicarF_2021.gene_families
library(ExperimentHub)
eh <- ExperimentHub()
query(eh, "2021-03-31.AsnicarF_2021.gene_families")
# ExperimentHub with 1 record
# snapshotDate(): 2021-10-19
# names(): EH5453
# package(): curatedMetagenomicData
# $dataprovider: NCBI
# $species: NA
# $rdataclass: SummarizedExperiment
# $rdatadateadded: 2021-04-08
# $title: 2021-03-31.AsnicarF_2021.gene_families
# $description: AsnicarF 2021 Gene Families
# $taxonomyid: NA
# $genome: NA
# $sourcetype: FASTQ
# $sourceurl: https://www.ncbi.nlm.nih.gov/sra
# $sourcesize: NA
# $tags: c("Homo_sapiens_Data", "MicrobiomeData",
#   "ReproducibleResearch") 
# retrieve record with 'object[["EH5453"]]' 
system.time(x <- eh[["EH5453"]])
# see ?curatedMetagenomicData and browseVignettes('curatedMetagenomicData') for documentation
# loading from cache
#   user  system elapsed
# 798.753  17.580 816.494
> format(object.size(x), units = "GB")
# [1] "15.3 Gb"
library(Matrix)
> dim(x)
# [1] 8322787    1098
system.time(writeMM(x, file = "AsnicarF_2021.gene_families.mm")) # https://math.nist.gov/MatrixMarket/
```

I haven't waited long enough to try, but you could probably succeed in writing a tsv file with another line like this (or transpose if you want 8 million columns):

```
write.table(as.matrix(x),  file = "AsnicarF_2021.gene_families.tsv", sep = "\t")
```

I also succeded the curatedMetagenomicData way up until the point of writing to file, but it also was slow and took more RAM (up to ~50GB). The file writing command still has not written a single line after ~20 minutes (possibly because of a promise from converting 8 million columns to data.frame) and I'm giving up on it now. But it's clear that working with a matrix of this size requires some special care to write to disk. I hope most analyses in R can be completed using the dgTMatrix format shipped in curatedMetagenomicData, because it becomes quite large to work with as a regular matrix. 

```
system.time(selist <- curatedMetagenomicData("AsnicarF_2021.gene_families", dryrun = FALSE))
# snapshotDate(): 2021-10-19
#         user   system  elapsed
# 1021.796   54.843 1111.229
dim(selist[[1]])
# [1] 8322787    1098
se <- selist[[1]][, se$Country == "GBR"]
library(Matrix)
system.time(df <- as.data.frame(as.matrix(t(assay(se)))))
#   user  system elapsed 
# 26.140   0.644  26.785 
system.time(readr::write_delim(df, file = "AsnicarF_2021.gene_families.tsv", delim = "\t"))
```

**Comment by lwaldron** [comment]
Checking at the end of the weekend, the `writeMM` command finished in about half an hour and produced a 21GB file:
```r
system.time(writeMM(x, file = "AsnicarF_2021.gene_families.mm")) # https://math.nist.gov/MatrixMarket/
    user   system  elapsed
1531.043   65.794 1688.245
> system("du -h AsnicarF_2021.gene_families.mm")
21G     AsnicarF_2021.gene_families.mm
```

but the readr::write_delim command is still running after ~2 days. So I think you can use the original R dgTMatrix sparse matrix format and work in R on a relatively high-memory machine, write a MatrixMarket file like above, or write an HDF5 file e.g. using the [rhdf5](https://www.bioconductor.org/packages/devel/bioc/vignettes/rhdf5/inst/doc/rhdf5.html) package. But these gene families files, especially one with 1000 samples, are just too large to work with in plain text tsv format, especially transposed so you have 8 million columns. Actually it might be more practical to write it in untransposed text file, replacing the last couple lines above with:
```r
system.time(mat <- as.matrix(assay(se)))
system.time(readr::write_delim(mat, file = "AsnicarF_2021.gene_families.tsv", delim = "\t"))
```

Let us know if you try it and have any success. I don't think there's anything more we can do right now to support export of these very large files, except some documentation of the issue.

**Comment by DPC7** [comment]
Hi @schifferl - I have followed your suggestion as provided in earlier threads. But, the problem persists. Anyway, is there a way to filter out the samples first and then try to export? I am using samples from GBR country and samples with 18.5 =<BMI <= 21.16522531 and samples with BMI >= 30. It total consists of 288 samples which may reduce the time and size and probably that subset of data may be exportable. If you please don't mind will please write me a code so that I can at least try to export that from my end?

Thanks for your constant support,
DPC7

**Comment by schifferl** [comment]
Hi @DPC7, I've tried a number to strategies myself to download the samples you're interested in on my machine (64 GB RAM also), but to no avail. Essentially, curatedMetagenomicDataTerminal/curatedMetagenomicData are both efficient and the operation will simply require a high memory machine as @lwaldron says (you can use one through AWS or GCP for cheap). This is a limitation of R and not something I can resolve without making a database implementation of curatedMetagenomicData (someday maybe), but for now you'll simply need much more RAM. Please leave this issue closed without further comment.
