### ISSUE TITLE
Unable to install curatedMetagenomicData

### ISSUE THREAD

**Issue by DPC7** [waldronlab/curatedMetagenomicDataCLI#14]
Hi @schifferl @lwaldron - I tried installing curatedMetagenomicData with the following code:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("curatedMetagenomicData")
```
But it shows the following errors:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/DirichletMultinomial/libs/DirichletMultinomial.so':
  /usr/local/lib/R/site-library/DirichletMultinomial/libs/DirichletMultinomial.so: invalid ELF header
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘curatedMetagenomicData’
* removing ‘/usr/local/lib/R/site-library/curatedMetagenomicData’

The downloaded source packages are in
	‘/tmp/Rtmpjh0YtN/downloaded_packages’
Warning message:
In .inet_warning(msg) :
  installation of package ‘curatedMetagenomicData’ had non-zero exit status
```
Can you please help me troubleshoot or suggest some other way to install?

**Comment by schifferl** [comment]
Hi @DPC7, you would like to install `curatedMetagenomicData` or `curatedMetagenomicDataTerminal`? Either way, it looks like your system has an issue with the `DirichletMultinomial` package (it is a `mia` dependency). Have a look at the `DirichletMultinomial` [repository](https://github.com/mtmorgan/DirichletMultinomial) and see if you have satisfied the `gls` system dependency requirement. If that doesn't resolve your issue, report back and include your `sessionInfo()`.
